install_all: install rec
install:
	pip install --user Sphinx


rec:
	pip install --user recommonmark
	pip install --user sphinx_rtd_theme
	pip install --user sphinx-markdown-tables
	pip install --user sphinx-autoapi

